---
- name: Ensure user
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.gid }}"
    groups: "{{ item.groups }}"
    append: true
    shell: /bin/bash
    state: present
  loop: "{{ users__users }}"

# TODO: Disable old keys.
- name: Ensure authorized SSH keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    comment: "{{ item.sshkeypub.split()[1:] | join(' ') }}"  # Remove the first word
    key: "{{ item.sshkeytype }} {{ item.sshkeypub }}"
  loop: "{{ users__users }}"
