---
- name: Ensure user group
  become: true
  ansible.builtin.group:
    state: present
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  loop: "{{ users__users }}"

- name: Ensure user
  become: true
  ansible.builtin.user:
    state: present
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.gid }}"
    groups: "{{ item.groups }}"
    append: true
    shell: /bin/bash
  loop: "{{ users__users }}"

# TODO: Disable old keys.
# See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#combining-objects-and-subelements
- name: Ensure authorized SSH keys
  become: true
  ansible.posix.authorized_key:
    state: present
    user: "{{ item.0.name }}"
    key: "{{ item.1.type }} {{ item.1.public_key }}"
    comment: "{{ item.1.public_key.split()[1:] | join(' ') }}"  # Remove the first word
  loop: "{{ users__users | subelements('authorized_ssh_keys') }}"
